image: node:14-alpine
stages:
  - prep
  - test
  - build

prep:
  stage: prep
  script:
    - yarn

test:
  stage: test
  script:
    - yarn nx test time

build:
  stage: build
  script:
    - echo 'Building...'
