image: node:14-alpine
stages:
  - prep
  - test
  - build

.cache:
  - key:
      files:
        - "yarn.lock"
    paths:
      - .yarn-cache/


prep:
  stage: prep
  extends: .cache
  script:
    - yarn install --cache-folder .yarn-cache

test:
  stage: test
  extends: .cache
  script:
    - yarn nx test time

build:
  stage: build
  script:
    - echo 'Building...'
