image: node:14-alpine
stages:
  - prep
  - test
  - build

prep:
  cache:
    - key:
        files:
          - "yarn.lock"
      paths:
        - .yarn-cache/
  stage: prep
  script:
    - yarn install --cache-folder .yarn-cache

test:
  stage: test
  script:
    - yarn nx test time

build:
  stage: build
  script:
    - echo 'Building...'
